### PR TITLE
Lebesgue.c: fix compile error

### PR DESCRIPTION
**Pull request by sw1sh**
Compiler was complaining: `error: subscripted value is neither array nor pointer`
I'm not sure this is correct, fixed by intuition only.

### CODE REVIEW

**Comment by mikeizbicki** [comment]
hmm... what C compiler does your system use?

It looks like the math is correct, but I'll have to check if the speed is affected by these changes at all.

**Comment by sw1sh** [comment]
I've checked `gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)` and `gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC)`, both gave the same error.

**Comment by mikeizbicki** [comment]
Thanks.  I'm using gcc-7.2 on Debian.  It must be that RedHat has more
strict flags turned on by default, which should make the code better.

Again, I think you're patch is correct, and I'll probably merge it.  I'll
do the performance tests I mentioned sometime next week to make sure it's
good.

**Comment by mikeizbicki** [comment]
Everything looked good!  Thanks a bunch for fixing this :)

**Pull request merged**
