### PR TITLE
Minor example updates

### PR DESCRIPTION
**Pull request by stites**
Hi @mikeizbicki — added some minor grammar / syntax tweaks as I was going through the first example. Feel free to ask for a subset of these if you don't agree with some of these changes.

Peanut gallery questions:
+ what if we have two strings that reference vector size which we want to alias -- is this possible?
+ how do you hyperlink text in literate haskell?
+ are you partial to literate haskell? It seems like we might be able to use [IHaskell][ihask] in the same interactive/reproducible way you are developing these examples, but we would also have these examples render in github and we could also use markdown (which seems more widespread than literate haskell).

[ihask]:https://github.com/gibiansky/IHaskell/blob/master/notebooks/Conjugate%20Gradient.ipynb

### CODE REVIEW

**Comment by mikeizbicki** [comment]
Thanks for the changes.  Some of them I like, and some I don't want to add.  So I'll go through this more carefully a bit later and merge them.


> what if we have two strings that reference vector size which we want to alias -- is this possible?

Yes, you can use an unlimited number of strings

> how do you hyperlink text in literate haskell?

I do it just like markdown

> are you partial to literate haskell? It seems like we might be able to use IHaskell in the same interactive/reproducible way you are developing these examples, but we would also have these examples render in github and we could also use markdown (which seems more widespread than literate haskell).

The only thing I don't like about literate haskell is that github doesn't render it properly as markdown.  I can change the extension to `.md`, but then ghc doesn't recognize the file as literate haskell :(  

One of my main requirements is that the documentation be viewable with just a text editor.  IIRC, IHaskell can't easily be edited/viewed with just a text editor, right?  Last time I checked it adds a bunch JSON throughout that makes it hard to edit.  If that's not the case, then I'd be happy to switch.

**Comment by stites** [comment]
wrt using IHaskell, it's definitely not version-control friendly for the same reason you just described; the JSON does get pretty gnarly. Perhaps this is a good mini-project — a browser plugin for viewing `.lhs` files on github.

Everything else sounds good — I'll take some time to update this example with some links to other source files / external references.

**Comment by stites** [comment]
@mikeizbicki — I just updated the example with some reference links and a note on the string alias'. Take a look!

Heads up: I don't think Travis is completely resetting since it errors when trying to link opt after the llvm install.

**Comment by mikeizbicki** [comment]
Sorry I missed your additions earlier.  I just merged them.

Travis had a problem due to a misconfiguration, but that's been fixed.

**Pull request merged**
