### PR TITLE
Added IntMap and patched src/Subhask/TemplateHaskell/Monad.hs

### PR DESCRIPTION
**Pull request by ehlemur**
Please compare src/SubHask/Compatibility/Containers.hs lines 233 to 237 vs 523 to 527

### CODE REVIEW

**Comment by mikeizbicki** [comment]
Thanks!  Commit a780405 looks great!

I'm not sure what 4c8f88c is doing though.  I think it might be a mistake?  If you remove that commit I'll merge.

**Comment by ehlemur** [comment]
4c8f88c is just and update from you I did because my fork was way behind.

**Comment by mikeizbicki** [comment]
Okay.  I'll try to merge this later today.  I have some changes locally that I'll have to update first.

**Comment by ehlemur** [comment]
Thanks!

**Comment by mikeizbicki** [comment]
I had changed the container class hierarchy a bit, so I updated the `IntMap` instances to reflect this.  I also added test cases.

**Pull request merged**
